Script started on 2023-01-17 23:15:41+01:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="232" LINES="6"]
[?2004h[01;32memeric@DellUb-Pawouet[00m : [01;34m~/WildCodeSchool/externatic[00m(B[m [[31mturbo(B[m] $ script bash[K[K[K[K[K[K[K[K[K[K[Kbash script.sh
[?2004lPHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20210902/pdo_mysql (/usr/lib/php/20210902/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/pdo_mysql.so (/usr/lib/php/20210902/pdo_mysql.so: undefined symbol: pdo_parse_params)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20210902/pdo_mysql (/usr/lib/php/20210902/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/pdo_mysql.so (/usr/lib/php/20210902/pdo_mysql.so: undefined symbol: pdo_parse_params)) in Unknown on line 0
[32mInstalling dependencies from lock file (including require-dev)[39m
[32mVerifying lock file contents can be installed on current platform.[39m
Nothing to install, update or remove
[30;43mPackage sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.[39;49m
[32mGenerating optimized autoload files[39m
[32m133 packages you are using are looking for funding.[39m
[32mUse the `composer fund` command to find out more![39m

Run [33mcomposer recipes[39m at any time to see the status of your Symfony recipes.

Executing script cache:clear [32m[OK][39m
Executing script assets:install public [32m[OK][39m
Executing script ckeditor:install [32m[OK][39m

[2K[1G[1myarn install v1.22.19[22m
[2K[1G[33mwarning[39m package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[2K[1G[2m[1/4][22m Resolving packages...
[1G⠁ [0K[1G⠂ @symfony/ux-live-component@file:vendor/symfony/ux-live-component/assets[0K[2K[1G[2K[1G[32msuccess[39m Already up-to-date.
[2K[1GDone in 0.36s.
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20210902/pdo_mysql (/usr/lib/php/20210902/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/pdo_mysql.so (/usr/lib/php/20210902/pdo_mysql.so: undefined symbol: pdo_parse_params)) in Unknown on line 0
[32mDropped database [39m[33m`externatic`[39m[32m for connection named [39m[33mdefault[39m
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20210902/pdo_mysql (/usr/lib/php/20210902/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/pdo_mysql.so (/usr/lib/php/20210902/pdo_mysql.so: undefined symbol: pdo_parse_params)) in Unknown on line 0
[32mCreated database [39m[33m`externatic`[39m[32m for connection named [39m[33mdefault[39m
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20210902/pdo_mysql (/usr/lib/php/20210902/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/pdo_mysql.so (/usr/lib/php/20210902/pdo_mysql.so: undefined symbol: pdo_parse_params)) in Unknown on line 0
[32m[notice] Migrating [39m[33mup[39m[32m to [39m[33mDoctrineMigrations\Version20230116154630[39m
[32m[notice] finished in [39m[33m3644.3[39m[32mms, used [39m[33m26M[39m[32m memory, [39m[33m43[39m[32m migrations executed, [39m[33m213[39m[32m sql queries[39m

PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20210902/pdo_mysql (/usr/lib/php/20210902/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/pdo_mysql.so (/usr/lib/php/20210902/pdo_mysql.so: undefined symbol: pdo_parse_params)) in Unknown on line 0

   [33m